[+] delete file or directory

diff --git a/lfrc b/lfrc
--- a/lfrc
+++ b/lfrc
@@ -7,32 +7,67 @@ set ignorecase true
 set icons true
 
 # Custom Functions
-cmd mkdir ${{
-  printf "Directory Name: "
+cmd create_dir ${{
+  echo -e ""
+  echo -n "$(tput setaf 3) Enter Directory Name  : "
   read ans
-  mkdir $ans
+  mkdir -p $ans
+  clear
 }}
 
-cmd mkfile ${{
-  printf "File Name: "
+cmd create_file ${{
+  echo -e ""
+  echo -n "$(tput setaf 3) Enter File Name  : "
   read ans
-  $EDITOR $ans
+  touch $ans
+  echo -e ""
+  echo -n "$(tput setaf 4) Edit file [y|n]  : "
+  read res
+  if [ "$res" = "y" || "$res" = "Y" || "$res" = "yes" || "$res" = "Yes" ]; then
+    $EDITOR $ans
+  fi
+  clear
 }}
 
-cmd setwallpaper ${{
-    cp "$f" ~/.config/wall.jpg
-    xwallpaper --zoom "$f"
-    betterlockscreen -u "$f" --fx
+cmd delete ${{
+  files=$(printf "$fx" | tr '\n' ';')
+  while [[ "$files" ]]; do
+    file=${files%%;*}
+
+    del=$(basename "$file")
+    echo -e ""
+    echo -n "$(tput setaf 1)  Are you sure you want to delete"
+    echo -n "$(tput setaf 3)  $del"
+    echo -n "$(tput setaf 1) [y|n] : "
+    read res
+    if [[ $res == "y" || $res == "Y" || $res == "yes" || $res == "Yes" ]]; then
+      rm -rf $del
+      clear
+      exit 1
+    fi
+      clear
+    exit 1
+  done
 }}
 
 # Archive bindings
 cmd unarchive ${{
-  case "$f" in
-      *.zip) unzip "$f" ;;
-      *.tar.gz) tar -xzvf "$f" ;;
-      *.tar.bz2) tar -xjvf "$f" ;;
-      *.tar) tar -xvf "$f" ;;
-      *) echo "Unsupported format" ;;
+  case $1 in
+    *.tar.bz2)    tar xjf $1    ;;
+    *.tar.gz)     tar xzf $1    ;;
+    *.bz2)        bunzip2 $1    ;;
+    *.rar)        unrar x $1    ;;
+    *.gz)         gunzip $1     ;;
+    *.tar)        tar xf $1     ;;
+    *.tbz2)       tar xjf $1    ;;
+    *.tgz)        tar xzf $1    ;;
+    *.zip)        unzip $1      ;;
+    *.Z)          uncompress $1 ;;
+    *.7z)         7z x $1       ;;
+    *.deb)        ar x $1       ;;
+    *.tar.xz)     tar xf $1     ;;
+    *.tar.zst)    unzstd $1     ;;
+    *)            echo "'$1' cannot be extracted" ;;
   esac
 }}
 
@@ -59,31 +94,27 @@ cmd restore_trash ${{
 map d
 map m
 
-map c $vscodium "$f"
-
 map au unarchive
-map ae $wine "$f"
 
 # Basic Functions
 map . set hidden!
-map dd trash
-map dr restore_trash
+# map dd trash
+# map dr restore_trash
 map p paste
 map x cut
 map y copy
 map <enter> open
 map R reload
-map mf mkfile
-map md mkdir
-map bg setwallpaper
+map mf create_file
+map md create_dir
+map dd delete
 map C clear
 
 # Movement
-map gD cd ~/documents
-map gd cd ~/downloads
-map gp cd ~/pictures
+map gr cd ~/rust
+map go cd ~/go
+map gD cd ~/Documents
+map gd cd ~/Downloads
 map gc cd ~/.config
-map gr cd ~/repos
-map gv cd ~/videos
 map gs cd ~/.local/bin
 map gt cd ~/.local/share/Trash/files
